server:
  port: 8085

spring:
  application:
    name: websocket-service
  data:
    redis:
      host: redis-service
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE}
  instance:
    prefer-ip-address: true

logging:
  level:
    com.momnect.websocketservice: DEBUG
    org.springframework.web.socket: DEBUG
