server:
  port: 0
  forward-headers-strategy: framework

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    active: dev
  application:
    name: chat-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

# Feign Client 설정
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      user-service:
        url: http://localhost:8000/api/v1/user-service

logging:
  level:
    com.momnect.chatservice: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    com.momnect.chatservice.command.client: DEBUG

# swagger
springdoc:
  packages-to-scan: com.momnect.chatservice
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
