# OpenAI API 관련 설정만 포함하는 별도 프로파일
spring:
  config:
    activate:
      on-profile: openai
  ai:
    openai:
      api-key:
      chat:
        options:
          model: gpt-3.5-turbo

# 커스텀 OpenAI 설정
openai:
  model: gpt-3.5-turbo
  max_tokens: 200
  temperature: 0.7
